// @flow

export const VALIDATION_STATUS_REQUEST = 'VALIDATION_STATUS_REQUEST';
export const VALIDATION_STATUS_FAILURE = 'VALIDATION_STATUS_FAILURE';
export const VALIDATION_STATUS_SUCCESS = 'VALIDATION_STATUS_SUCCESS';
